// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSOA.Services.Blog.Entities;

namespace Blog.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20190203214108_AddCreatedToBlog")]
    partial class AddCreatedToBlog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new { Id = new Guid("0a376ca5-33bf-48ce-a7af-d601fc45160e"), Content = "Content-1", Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatorId = new Guid("b2576551-7c88-49e4-ab58-1cffe2cbd17a"), Title = "Title-1" },
                        new { Id = new Guid("9494a38c-0a0b-4fd9-84de-f7f62a76706a"), Content = "Content-2", Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatorId = new Guid("f6b73ef1-f626-4475-960b-0a2ff1a17b7f"), Title = "Title-2" },
                        new { Id = new Guid("0139bd0e-44de-4a75-9146-8841137787e5"), Content = "Content-3", Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatorId = new Guid("4108fd4e-306e-4936-89ec-06a7b356a895"), Title = "Title-3" }
                    );
                });

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BlogId");

                    b.Property<string>("Content");

                    b.Property<Guid>("CreatorId");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { Id = new Guid("ed284137-a8e7-4246-b92c-ffd81d73ccf8"), BlogId = new Guid("0a376ca5-33bf-48ce-a7af-d601fc45160e"), Content = "Content", CreatorId = new Guid("fa6e457e-15e0-4fb1-a450-c60a7eaead6b") }
                    );
                });

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Post", b =>
                {
                    b.HasOne("SchoolSOA.Services.Blog.Entities.Blog", "Blog")
                        .WithMany()
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
