// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSOA.Services.Blog.Entities;

namespace Blog.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20190111104340_AddPostAndSeedOne")]
    partial class AddPostAndSeedOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new { Id = new Guid("3bee4b2b-6426-4838-9ed0-b7a4d67feedc"), Content = "Content-1", CreatorId = new Guid("a2d0f792-530e-47a6-a22d-5f5ea7f6ebe0"), Title = "Title-1" },
                        new { Id = new Guid("c4752618-8374-42c8-9c40-6bff8ffbb027"), Content = "Content-2", CreatorId = new Guid("6a6ac338-7a25-4049-a7c7-9de2b922ae80"), Title = "Title-2" },
                        new { Id = new Guid("cff9d13f-ce97-40cd-a51d-1df08706b8cd"), Content = "Content-3", CreatorId = new Guid("f796f035-d9da-4c87-8c9b-6a75074b46d1"), Title = "Title-3" }
                    );
                });

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BlogId");

                    b.Property<string>("Content");

                    b.Property<Guid>("CreatorId");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { Id = new Guid("785e43e4-3400-49ff-a249-7a2c96d75890"), BlogId = new Guid("e9f1ad0b-e281-44db-b4fc-c3c2a23919ff"), Content = "Content", CreatorId = new Guid("ee825f96-9522-4c6e-ae5c-383ad3f68668") }
                    );
                });

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Post", b =>
                {
                    b.HasOne("SchoolSOA.Services.Blog.Entities.Blog", "Blog")
                        .WithMany()
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
