// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSOA.Services.Blog.Entities;

namespace Blog.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20190204135822_AddCreatorNameToBlogAndPost")]
    partial class AddCreatorNameToBlogAndPost
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("CreatorName");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new { Id = new Guid("d8c97f6b-eba1-40f5-b1c9-c456d41a1446"), Content = "Content-1", Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatorId = new Guid("ae7b3b9c-5eb9-4642-a215-e2942243d55e"), CreatorName = "Creator 1", Title = "Title-1" },
                        new { Id = new Guid("7241bc8b-b4c6-4ffc-8754-d192904b93fe"), Content = "Content-2", Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatorId = new Guid("e13c029c-090d-4366-9dda-48876ddddce1"), CreatorName = "Creator 2", Title = "Title-2" },
                        new { Id = new Guid("aba681c5-5414-465a-b366-143c2c2ebc00"), Content = "Content-3", Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), CreatorId = new Guid("cdb86c22-4ce5-4070-960e-251ef0c1935e"), CreatorName = "Creator 3", Title = "Title-3" }
                    );
                });

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BlogId");

                    b.Property<string>("Content");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("CreatorName");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { Id = new Guid("95fc888d-0e0c-4bf6-b106-1de2f56572fd"), BlogId = new Guid("d8c97f6b-eba1-40f5-b1c9-c456d41a1446"), Content = "Content", CreatorId = new Guid("62c95ccf-89ab-4832-acb9-c5e09cda1e68") }
                    );
                });

            modelBuilder.Entity("SchoolSOA.Services.Blog.Entities.Post", b =>
                {
                    b.HasOne("SchoolSOA.Services.Blog.Entities.Blog", "Blog")
                        .WithMany()
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
