version: '3.2'

services:
  gateway:
    image: microsoft/dotnet:2.1-sdk
    ports:
      - "5010:80"
    volumes:
      - ./Gateway:/app
    working_dir: /app
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - blog
      - identity
      - badge
  
  blog:
    image: microsoft/dotnet:2.1-sdk
    ports:
      - "5001:80"
    volumes:
      - ./:/app
    working_dir: /app/Services/Blog
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - blog-db
      - rabbitmq
  blog-db:
    image: "microsoft/mssql-server-linux:2017-CU8"
    environment:
        SA_PASSWORD: "Password1;"
        ACCEPT_EULA: "Y"
  
  identity:
    image: microsoft/dotnet:2.1-sdk
    ports:
      - "5002:80"
    volumes:
      - ./:/app
    working_dir: /app/Services/Identity
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - identity-db
      - rabbitmq
  identity-db:
    image: "microsoft/mssql-server-linux:2017-CU8"
    environment:
        SA_PASSWORD: "Password1;"
        ACCEPT_EULA: "Y"

  badge:
    image: microsoft/dotnet:2.1-sdk
    ports:
    - "5003:80"
    volumes:
    - ./:/app
    working_dir: /app/Services/Badge
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
    - badge-db
    - rabbitmq
  badge-db:
    image: "microsoft/mssql-server-linux:2017-CU8"
    environment:
      SA_PASSWORD: "Password1;"
      ACCEPT_EULA: "Y"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    container_name: rabbitmq