version: '3.2'

services:
  gateway:
    image: microsoft/dotnet:2.1-sdk
    ports:
      - "5000:80"
    volumes:
      - ./Gateway:/app
    working_dir: /app/Gateway
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - blog
      - identity
  
  blog:
    image: microsoft/dotnet:2.1-sdk
    ports:
      - "5001:80"
    volumes:
      - ./:/app
    working_dir: /app/Services/Blog
    command: [ 'dotnet', 'watch', 'run' ]
  
  identity:
    image: microsoft/dotnet:2.1-sdk
    ports:
      - "5002:80"
    volumes:
      - ./:/app
    working_dir: /app/Services/Identity
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - identity-db
  identity-db:
    image: "microsoft/mssql-server-linux:2017-CU8"
    environment:
        SA_PASSWORD: "Password1;"
        ACCEPT_EULA: "Y"